parameters:
    env(MONGODB_URL): ''
    env(MONGODB_DB): ''
    uploads_directory: '%kernel.project_dir%/public/uploads'
    mercure.public_url: '%env(MERCURE_PUBLIC_URL)%'
    mercure.jwt_secret: '%env(MERCURE_JWT_SECRET)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'

    Symfony\Component\Mercure\HubInterface:
        alias: 'mercure.hub.default'