version: '3.8'

services:
  ###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-16}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/postgresql/data:rw
    ports:
      - "5432:5432"  # Exposition du port 5432 pour PostgreSQL
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"  # Exposition du port SMTP
      - "8025:8025"  # Exposition du port web Mailpit
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  ###< symfony/mailer ###

  ###> symfony/mercure-bundle ###
  mercure:
    image: dunglas/mercure
    restart: unless-stopped
    environment:
      # Les clés JWT doivent correspondre à celles définies dans .env et mercure.yaml
      MERCURE_PUBLISHER_JWT_KEY: 'ThisIsASecureKeyWithAtLeast32Characters123'
      MERCURE_PUBLISHER_JWT_ALG: 'HS256'
      MERCURE_SUBSCRIBER_JWT_KEY: 'ThisIsASecureKeyWithAtLeast32Characters123'
      MERCURE_SUBSCRIBER_JWT_ALG: 'HS256'
      # Configuration des CORS pour permettre les connexions depuis votre application
      MERCURE_EXTRA_DIRECTIVES: |
        cors_origins http://127.0.0.1:8000 http://localhost:8000
        # Permettre la publication depuis votre app
        publish_origins http://127.0.0.1:8000 http://localhost:8000
        # Permettre les connexions anonymes pour les abonnés
        anonymous
        # Activer les abonnements
        subscriptions
    command: /usr/bin/caddy run --config /etc/caddy/dev.Caddyfile
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/healthz"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - ./dev.Caddyfile:/etc/caddy/dev.Caddyfile
      - mercure_data:/data
      - mercure_config:/config
    ports:
      - "3000:80"  # Exposition du port 80 de Mercure sur le port 3000
  ###< symfony/mercure-bundle ###

  ###> Symfony App ###
  app:
    image: symfony-cli
    container_name: symfony_app
    working_dir: /app
    environment:
      # Ajout des variables d'environnement nécessaires
      MERCURE_URL: 'http://mercure/.well-known/mercure'
      MERCURE_PUBLIC_URL: 'http://localhost:3000/.well-known/mercure'
      MERCURE_JWT_SECRET: 'ThisIsASecureKeyWithAtLeast32Characters123'
    volumes:
      - .:/app
    ports:
      - "8000:8000"  # Exposition du port 8000 pour Symfony
    depends_on:
      - database
      - mercure
  ###< Symfony App ###

volumes:
  ###> doctrine/doctrine-bundle ###
  database_data:
  ###< doctrine/doctrine-bundle ###

  ###> symfony/mercure-bundle ###
  mercure_data:
  mercure_config:
  ###< symfony/mercure-bundle ###